Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"
  
  config.vm.hostname = "dliuzzoS"
  config.vm.synced_folder "./p1", "/home/vagrant/p1", create: true
end