Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  config.vm.define "dliuzzoS" do |control|
    control.vm.hostname = "dliuzzoS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.synced_folder "./app", "/home/vagrant/app", create: true

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "dliuzzoS"]
      v.memory = 1024    # RAM in MB (e.g., 1024 = 1 GB)
      v.cpus = 2         # Number of CPU cores
    end

    control.vm.provision "shell", path: "server-dependencies.sh"
  end
end