Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202502.21.0"

  config.vm.define "dliuzzoS" do |control|
    control.vm.hostname = "dliuzzoS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.synced_folder "./conf", "/home/vagrant/conf", create: true

    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "dliuzzoS"]
      v.memory = 1024    
      v.cpus = 2         
    end

    control.vm.provision "shell", path: "./scripts/server-dependencies.sh"

    control.vm.provision "shell", name: "init", path: "./scripts/init.sh"
  end
end